version: '3'

services:
  oracle-db:
    image: container-registry.oracle.com/database/enterprise:21.3.0.0
    container_name: oracle
    environment:
      - ORACLE_SID=ORCLCDB
      - ORACLE_PDB=ORCLPDB1
      - ORACLE_PWD=Oracle_123
    ports:
      - 1521:1521
    volumes:
      - oracle-data:/opt/oracle/oradata
      - oracle-backup:/opt/oracle/backup
    healthcheck:
      test: ["CMD", "sqlplus", "-L", "sys/Oracle_123@//localhost:1521/ORCLCDB as sysdba", "@healthcheck.sql"]
      interval: 30s
      timeout: 10s
      retries: 5

  spark:
    image: bitnami/spark:latest
    container_name: spark_container
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4040:4040"  # Spark UI
    environment:
      - SPARK_MODE=master

volumes:
  oracle-data:
  oracle-backup: